### ISSUE TITLE
remove redundant header

### ISSUE THREAD

**Issue by omarcostahamido** [musica-interdisciplinar/musica-interdisciplinar.github.io#4]
i can try to figure this out later today:

the cayman header seems a bit redundant right now.
it would be nice to simply remove it and start the page with the image.

**Comment by ntrocado** [comment]
concordo... se calhar outro theme podia funcionar melhor, mas entretanto o header sai fora

fixed by https://github.com/musica-interdisciplinar/musica-interdisciplinar.github.io/commit/5fc68e0666764e09113e77849e3240f1ff189d00
